<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTENqG7S\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTENqG7S/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTENqG7S.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTENqG7S\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTENqG7S\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TENqG7S',
    'container.build_id' => 'e053982b',
    'container.build_time' => 1584801845,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTENqG7S');
